declare module 'markdown-it-emoji'
declare module 'markdown-it-imsize'
declare module 'markdown-it-github-headings'
declare module 'markdown-it-container'
declare module 'vue-codemirror'
declare module 'element-ui/lib/locale/lang/en'
